trigger:mender-dist-packages:
  stage: trigger:packages
  needs: []
  rules:
    - if: $BUILD_MENDER_DIST_PACKAGES == "true"
  variables:
    # Unset DOCKER_ variables, the pipeline will execute on shared runners
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_CERT_PATH: ""
    DOCKER_TLS_VERIFY: ""
    DOCKER_TLS_CERTDIR: ""

    # Mender release tagged versions:
    MENDER_VERSION: $MENDER_REV
    MENDER_CONNECT_VERSION: $MENDER_CONNECT_REV
    MENDER_MONITOR_VERSION: $MONITOR_CLIENT_REV
    # Obs! mender-configure-module is not part of the release (from release_tool eyes)
    # so it cannot be passed downstream to mender-dist-packages.
    # For this repo, we use the old flow of tag in repo -> trigger in mender-dist-packages
    #MENDER_CONFIGURE_VERSION

    # Mode: "build and publish" or "build and test"
    TEST_MENDER_DIST_PACKAGES: $TEST_MENDER_DIST_PACKAGES
    PUBLISH_MENDER_DIST_PACKAGES_AUTOMATIC: $PUBLISH_RELEASE_AUTOMATIC
  trigger:
    project: Northern.tech/Mender/mender-dist-packages
    branch: $MENDER_DIST_PACKAGES_REV
    strategy: depend
