trigger:mender-dist-packages:
  stage: trigger:packages
  needs: []
  rules:
    - if: $BUILD_MENDER_DIST_PACKAGES == "true"
  variables:
    # Mender release tagged versions:
    MENDER_VERSION: $MENDER_REV
    MENDER_CONNECT_VERSION: $MENDER_CONNECT_REV
    MENDER_MONITOR_VERSION: $MONITOR_CLIENT_REV
    MENDER_CONFIGURE_VERSION: $MENDER_CONFIGURE_MODULE_REV

    # Mode: "build and publish" or "build and test"
    TEST_MENDER_DIST_PACKAGES: $TEST_MENDER_DIST_PACKAGES
    PUBLISH_MENDER_DIST_PACKAGES_AUTOMATIC: $PUBLISH_RELEASE_AUTOMATIC
  trigger:
    project: Northern.tech/Mender/mender-dist-packages
    branch: $MENDER_DIST_PACKAGES_REV
    strategy: depend
